### ISSUE TITLE
/bin/sh: ./bld.sh: Permission denied

### ISSUE THREAD

**Issue by anuphalarnkar** [jlinoff/gcc-4.9.2-boost-1.57#2]
OS/Arch: RHEL 7.1/ppc64le
I am a root user. I run the following command "make" as given in your instructions. I get this error below..

./bld.sh 2>&1 | tee logs/bld-$(date +'%Y%m%d-%H%M%S').log
/bin/sh: ./bld.sh: Permission denied

Thanks,
Anup Halarnkar

**Comment by hugdx** [comment]
You need add permission  for bld.sh before run
````
 chmod +x bld.sh
````

**Comment by jlinoff** [comment]
Thank you. This was fixed in the last commit.
