### ISSUE TITLE
problem in installing gcc-4.9.2-boost-1.57

### ISSUE THREAD

**Issue by haghakhani** [jlinoff/gcc-4.9.2-boost-1.57#4]
Hello,

Thank you for providing the very usefull bash script to install gcc-4.9.2-boost-1.57 in local space. I was trying to install in on CentOS 6.7 (Final), but I got the following error:

 'c++' language required by 'go' in stage 1; enabling
*** This configuration is not supported in the following subdirectories:
     gnattools target-libada target-libgfortran target-zlib target-libjava target-libobjc target-boehm-gc
    (Any other directories should still work fine.)
checking for default BUILD_CONFIG... bootstrap-debug
checking for --enable-vtable-verify... no
/usr/bin/ld: crt1.o: No such file: No such file or directory
collect2: ld returned 1 exit status
configure: error: I suspect your system does not have 32-bit developement libraries (libc and headers). If you have them, rerun configure with --enable-multilib. If you do not have them, and want to build a 64-bit-only compiler, rerun configure with --disable-multilib.
STATUS = 1

I modified the bash script to configure and install with --disable-multilib flag but I got the same problem. I was wondering if you can please help me with this issue.

Regards,

**Comment by jlinoff** [comment]
Do you have the CentOS development packages installed? It looks like you might be missing the native gcc/g++ compilers. You might be able to fix this by running `yum groupinstall "Development Tools"`.

**Comment by hugdx** [comment]
with CentOS 6.7 (i am using too), i have been install ``g++ 4.8.2`` with ``devtools-2``.
This is my command to install this. maybe it can be help you

```
wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
yum install devtoolset-2-gcc devtoolset-2-binutils
yum install devtoolset-2-gcc-gfortran

# enable g++ before you want to compile php-cpp (only need 1 first time every times logged in ssh)
scl enable devtoolset-2 bash

# see more at http://braaten-family.org/ed/blog/2014-05-28-devtools-for-centos/
```

**Comment by jlinoff** [comment]
What happens when you type `g++ --version` after running the above commands?

**Comment by haghakhani** [comment]
Thank you for your suggestions. Unfortunately, I'm not the super user on this computer but asked the administrator to install these packages. He installed Development Tools packages but told may be CentOS 6.7  is too old to install gcc 4.9.2, and unfortunately, they do not have any plan to update it. Probably, I'll try to install an older version of gcc with one of the other bash scripts that you wrote.
g++ version is still the old one.

**Comment by jlinoff** [comment]
I see. I have not tried gcc-4.9.2 on CentOS 6.7. I have ysed gcc-4.8.3 and gcc-4.8.4 on that platform.

Good luck.

**Comment by jlinoff** [comment]
Have you resolved this? If so, can I close this issue?

**Comment by haghakhani** [comment]
Thank you for your following up.
No, even after installing those packages I was unable to build it. I think I have to use older versions.
BTW, you can close this issue.
Thanks

**Comment by jlinoff** [comment]
Sorry to hear that. Thanks for letting close this issue.
